### ISSUE TITLE
URL 404

### ISSUE THREAD

**Issue by ErinWeisbart** [Synthaze/utilsovs#2]
The URL linked [oglcnac.com](https://oglcnac.com/) in your "About" for this repo does not exist?

**Comment by Synthaze** [comment]
The URL in the "About" section was changed to [oglcnac.mcw.edu](url). 

The URL [oglcnac.com](url) should redirect to [oglcnac.mcw.edu](url), which was apparently working in http but not https. The record was updated with SSL enabled and this change should be propagated within 48hrs.
